version: '3.9'

services:
  go-app:
    container_name: go-app
    image: eastor112/go-app:1.0.1
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=HotelDB sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: HotelDB
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
